---
- hosts: server
  become: true
  tasks:
  - name: Install nfs-utils
    yum:
      name: nfs-utils
  - name: Create directories
    file:
      path: "{{ item.path }}"
      state: directory
      mode: "{{ item.mode }}"
    loop: "{{ nfs_mounts }}"
  - name: Configure exports filesystems
    blockinfile:
      path: /etc/exports
      marker: "# {mark} ANSIBLE MANAGED BLOCK NFS"
      block: |
        {% for item in nfs_mounts %}
        {{ item.path }} {{ item.clients | join(' ') }}
        {% endfor %}
    notify: restart nfs
  - name: Enable firewalld
    become: true
    systemd:
      name: firewalld
  - name: Create rule for firewalld
    become: true
    firewalld:
      service: nfs
      permanent: true
      state: enabled
  handlers:
  - name: restart nfs
    systemd:
      name: nfs-server.service
      enabled: true
      daemon_reload: true
      state: restarted

- hosts: client
  become: true
  tasks:
  - name: Create directories
    file:
      path: "{{ item.mount_point }}"
      state: directory
    loop: "{{ nfs_mounts }}"
  - name: Config mount point
    mount:
      src: "{{ item.server }}:{{ item.path }}"
      path: "{{ item.mount_point }}"
      fstype: nfs
      opts: "{{ item.options | default('defaults') }}"
      state: mounted
    loop: "{{ nfs_mounts }}"
